# Use Tomcat 10 with Java 17
FROM tomcat:10.1-jdk17

# Copy WAR into Tomcat webapps folder
COPY target/Docker_app-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

# Expose default Tomcat port
EXPOSE 8080